<script setup lang="ts">
import { computed } from 'vue'
import { useRoute } from 'vue-router'
import JobCard from '@/components/public/JobCard.vue'
import { getCompany, jobs } from '@/data/catalog'

const route = useRoute()
const company = computed(() => getCompany(String(route.params.id)))
const companyJobs = computed(() => jobs.filter((job) => job.company === company.value.name))
</script>

<template>
  <section class="bg-[#f3f1ff] pb-12">
    <div class="mx-auto max-w-[1440px] px-6 pt-7 sm:px-10 lg:px-[108px]"><nav class="flex items-center gap-2 text-sm text-[#66739d]"><router-link to="/companies" class="hover:text-[#715cdf]">Companies</router-link><span>/</span><span>{{ company.name }}</span></nav><div class="relative mt-7 h-48 overflow-hidden rounded-3xl bg-[#0b2b82] sm:h-60"><div class="absolute -right-12 -top-24 size-80 rounded-full border-[42px] border-[#244ba2]"></div><div class="absolute bottom-[-80px] left-[28%] size-56 rounded-full bg-[#7b66ff]/40 blur-2xl"></div><div class="absolute left-8 top-8 text-sm font-semibold uppercase tracking-[0.18em] text-[#c7c0ff]">Company profile</div></div><div class="relative mx-4 -mt-12 rounded-2xl border border-[#e8e4f4] bg-white p-6 shadow-[0_14px_35px_rgba(30,35,90,0.08)] sm:mx-8 sm:p-7"><div class="flex flex-col gap-5 sm:flex-row sm:items-center"><div class="flex size-20 shrink-0 items-center justify-center rounded-2xl" :style="{ backgroundColor: company.accent }"><img :src="company.logo" :alt="`${company.name} logo`" class="size-12 object-contain" /></div><div class="flex-1"><div class="flex flex-wrap items-center gap-3"><h1 class="text-3xl font-semibold tracking-[-0.04em] text-[#0b2b82]">{{ company.name }}</h1><span class="inline-flex items-center gap-1 rounded-full bg-[#edf9f0] px-2.5 py-1 text-xs font-semibold text-[#278144]"><svg class="size-3.5" fill="currentColor" viewBox="0 0 20 20"><path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-7 7a1 1 0 01-1.414 0l-3-3a1 1 0 011.414-1.414L9 11.586l6.293-6.293a1 1 0 011.414 0z" clip-rule="evenodd" /></svg>Verified</span></div><p class="mt-2 text-sm text-[#60709a]">{{ company.industry }} · {{ company.location }}</p></div><a :href="`https://${company.website}`" target="_blank" rel="noreferrer" class="rounded-xl border border-[#dcd6f2] px-4 py-2.5 text-center text-sm font-semibold text-[#463a9c] transition hover:border-[#7b66ff] hover:bg-[#f7f5ff]">Visit website ↗</a></div></div></div>
  </section>

  <section class="mx-auto grid max-w-[1440px] gap-10 px-6 py-12 sm:px-10 lg:grid-cols-[minmax(0,1fr)_300px] lg:px-[108px] lg:py-16">
    <article><section><p class="text-sm font-semibold uppercase tracking-[0.16em] text-[#7b66ff]">About {{ company.name }}</p><h2 class="mt-3 text-3xl font-semibold tracking-[-0.035em] text-[#0b2b82]">Work with people who care about the details.</h2><p class="mt-5 max-w-3xl text-base leading-8 text-[#53669a]">{{ company.about }}</p></section><section class="mt-12"><h2 class="text-2xl font-semibold text-[#0b2b82]">Open roles</h2><p class="mt-2 text-sm text-[#65739b]">A few of the ways you can make an impact at {{ company.name }}.</p><div v-if="companyJobs.length" class="mt-6 grid gap-5 md:grid-cols-2"><JobCard v-for="job in companyJobs" :key="job.id" :job="job" compact /></div><div v-else class="mt-6 rounded-2xl border border-dashed border-[#ddd7ef] bg-[#fbfaff] px-6 py-10 text-center text-sm text-[#67749c]">There are no listed openings today. Check back soon.</div></section></article>
    <aside class="h-fit space-y-5 lg:sticky lg:top-6"><div class="rounded-2xl border border-[#e7e4f4] bg-[#fcfbff] p-6"><h2 class="font-semibold text-[#0b2b82]">At a glance</h2><dl class="mt-5 space-y-4 text-sm"><div><dt class="text-[#7a86a8]">Industry</dt><dd class="mt-1 font-medium text-[#324178]">{{ company.industry }}</dd></div><div><dt class="text-[#7a86a8]">Company size</dt><dd class="mt-1 font-medium text-[#324178]">{{ company.size }}</dd></div><div><dt class="text-[#7a86a8]">Founded</dt><dd class="mt-1 font-medium text-[#324178]">{{ company.founded }}</dd></div><div><dt class="text-[#7a86a8]">Headquarters</dt><dd class="mt-1 font-medium text-[#324178]">{{ company.location }}</dd></div></dl></div><div class="rounded-2xl bg-[#f3f1ff] p-6"><h2 class="font-semibold text-[#0b2b82]">What they offer</h2><ul class="mt-4 space-y-3"><li v-for="benefit in company.benefits" :key="benefit" class="flex items-center gap-2 text-sm text-[#56679b]"><span class="size-1.5 rounded-full bg-[#7b66ff]"></span>{{ benefit }}</li></ul></div></aside>
  </section>
</template>
